language: node_js
node_js:
  - 0.8
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#angularjs"
env:
  - JASMINE=node_modules/adapter/lib/jasmine.js
  - JASMINE_ADAPTER=node_modules/adapter/jasmine.js
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm link
  - grunt build
script:
  - grunt test